# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='home, Street, City, District, Country', max_length=1024)),
                ('birth_date', models.DateField()),
                ('image', models.FileField(upload_to='doctors/image')),
                ('description', models.TextField(max_length=1024)),
                ('works_from', models.TimeField()),
                ('works_to', models.TimeField()),
                ('pos', models.ManyToManyField(related_name='doctor_position', to='HealUsers.CategoryOfDocs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='select images like *.jpg, *.png', upload_to='patients/image')),
                ('phone_number', models.CharField(help_text='ex: +998935741369', max_length=13)),
                ('birth_date', models.DateField()),
                ('about_illness', models.TextField(max_length=1024)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfIllness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ex: Tuberculosis', max_length=255)),
                ('image', models.FileField(blank=True, help_text='select images like *.jpg, *.png', upload_to='Illness/image', validators=['*.jpg', '*.png'])),
                ('description', models.TextField(max_length=2048)),
            ],
        ),
    ]
