# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealUsers', '0003_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='about_illness',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.FileField(blank=True, help_text='select images like *.jpg, *.png', upload_to='patients/image'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='ex: +998935741369', max_length=13),
        ),
    ]
