# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealForum', '0002_auto_20170422_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='description',
        ),
        migrations.AddField(
            model_name='comment',
            name='description_comment',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
