# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealForum', '0003_auto_20170422_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='HealForum.Post'),
        ),
    ]
