# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HealUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('for_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealUsers.Doctor')),
                ('from_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='HealUsers.Patient')),
                ('illness', models.ManyToManyField(blank=True, related_name='patient_illness', to='HealUsers.TypeOfIllness', verbose_name='illnesses')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ex: trimol', max_length=255)),
                ('description', models.TextField(help_text='ex: for headache', max_length=2048)),
                ('for_illness', models.ManyToManyField(help_text='select types', related_name='drug_illness', to='HealUsers.TypeOfIllness', verbose_name='illnesses')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='suggested_drugs',
            field=models.ManyToManyField(related_name='appointment_suggestion', to='HealTech.Drug'),
        ),
    ]
